- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: 
      name: 
        # spell check
      - aspell
        # epub
      - calibre
        # pdf
      - evince
      - firefox
      - gvim
      - mupdf
        # png
      - nomacs
        # screen control
      - redshift
      - srm
        # Latex
      # - texlive-recommended
      - texlive-base
      - texlive-extra-utils
      - vifm
      - vlc
        # for inverting screen
      - xcalib
        # pdf printing
      - zathura
