- hosts: localhost
  become: true
  tasks:
  - name: Install spell checker
    apt: 
      name: aspell
  
  - name: Install epub editor 
    apt: 
      name: calibre

  - name: Install fast pdf viewer
    apt: 
      name: mupdf

  - name: Install pdf viewer for non-standard printing
    apt: 
      name: zathura

  - name: Install another pdf viewer for compatibility
    apt: 
      name: evince

  - name: Install git
    apt: 
      name: git-all

  - name: Install background setter
    apt: 
      name: feh

  - name: Install graphical vim
    apt: 
      name: vim-gtk

  - name: Install vim-like file manager 
    apt: 
      name: vifm

  - name: Install non-distorting .png viewer
    apt: 
      name: nomacs

  - name: Install the package that solved your vpn
    apt: 
      name: 
      # - resolvconf

  - name: Install browsers
    apt: 
      name:
      - chromium-browser
      - firefox

  - name: Install screen control apps 
    apt: 
      name:
      - redshift
      - xcalib

  - name: Install Latex
    apt: 
      name:
      # - texlive-recommended
      - texlive-base
      - texlive-extra-utils
     
  - name: Install Nautilus for USB plug and play 
    apt: 
      name: nautilus
     
  - name: Install secure-delete
    apt: 
      name: secure-delete
     




