- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: 
      name: 
        # spell check
      - aspell
        # epub
      - calibre
        # pdf
      - chromium-browser
      - evince
        # set background with
      - feh
      - firefox
      - git-all
      - mupdf
        # png
      - nomacs
        # screen control
      # - resolvconf
      - redshift
        # Latex
      # - texlive-recommended
      - texlive-base
      - texlive-extra-utils
      - vifm
         # gvim
      - vim-gtk
        # invert screen
      - xcalib
        # pdf printing
      - zathura
